# jdbc url connects the mysql db
spring.datasource.url=${MYSQL_URL}

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# hibernate automatically create based on jpa which create in the spring boot
spring.jpa.hibernate.ddl-auto=update